cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'


urlpatterns = [
    path('',views.cart_detail , name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/',views.cart_remove , name='cart_remove'),
]

coupons/urls.py
from django.urls import path
from . import views

app_name = 'coupons'

urlpatterns = [
	path('apply/', views.coupon_apply, name='apply'),

]

orders/urls.py
from django.urls import path 
from . import views 
from django.utils.translation import gettext_lazy as _


app_name = 'orders'

urlpatterns = [
    path(_('create/'), views.order_create, name='order_create'),
    path('admin/order/<int:order_id>/', views.admin_order_detail, name='admin_order_detail'),
    path('admin/order/<int:order_id>/pdf/', views.admin_order_pdf, name='admin_order_pdf'),


]

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'


urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
]

website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _



urlpatterns =  i18n_patterns(
    path(_('admin/'), admin.site.urls),
    path('rosetta/', include('rosetta.urls')),

    path(_('cart/'), include('cart.urls', namespace='cart')),
    path(_('orders/'), include('orders.urls', namespace='orders')),
    path(_('coupons/'), include('coupons.urls', namespace='coupons')),
    path('', include('shop.urls', namespace='shop')),
)
if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cart/models.py
from django.db import models
from shop.models import Product
# Create your models here.

cart/forms.py
from django import forms 
from django.utils.translation import gettext_lazy as _

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]

class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int,label=_('Quantity'))
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .cart import Cart
from .forms import CartAddProductForm 
from django.views.decorators.http import require_POST
from shop.models import Product 
from coupons.forms import CouponApplyForm


# Create your views here.

@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'],update_quantity=cd['update'])
    
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'],'update':True})
    coupon_apply_form = CouponApplyForm()


    return render(request, 'cart/detail.html', {'cart': cart, 'coupon_apply_form':coupon_apply_form})

templates/cart/detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Cart{% endblock title %}
  
{% block content %}

<div class="container mb-5" style="margin-top:100px">
<h1 class=" mb-5" >Your Shopping Cart </h1>
<table class="table table-striped">
  <thead>
    <tr>
  <th>Image</th>
  <th>Product</th>
  <th>Quantity</th>
  <th>Remove</th>
  <th>Unit price</th>
  <th>Price</th>

    </tr>
  </thead>
  <tbody>
    {% for item in cart %}
{% with product=item.product %}
<tr>
		<td>
		<a href="{{ product.get_absolute_url }}">
		<img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/sample.jpg' %}{% endif %}">
		</a>
		</td>
		<td>{{ product.name }}</td>
		<td><form action="{% url 'cart:cart_add' product.id %}" method="post">
		{{ item.update_quantity_form.quantity }}
		{{ item.update_quantity_form.update }}
		<input type="submit" class="p-1"  value="Update" style='color:#fff; background-color:#2879d1; border:none;'>
		{% csrf_token %}
</form>
</td>
		<td><a href="{% url 'cart:cart_remove' product.id%}">Remove</a></td>
		<td class="num">${{ item.price }}</td>
		<td class="num">${{ item.total_price }}</td>
	</tr>
{% endwith %}
{% endfor %}

{% if cart.coupon %}
<tr class="subtotal">
<td>Subtotal</td>
<td colspan="4"></td>
<td class="num">${{ cart.get_total_price|floatformat:2 }}</td>
</tr>
<tr>
<td>
"{{ cart.coupon.code }}" coupon
({{ cart.coupon.discount }}% off)
</td>
<td colspan="4"></td>
<td class="num neg">
- ${{ cart.get_discount|floatformat:2 }}
</td>
</tr>
{% endif %}
<tr class="total">
<td>Total</td>
<td colspan="4"></td>
<td class="num">
${{ cart.get_total_price_after_discount|floatformat:2 }}
</td>
</tr>


  </tbody>
</table>
<h5>Apply a coupon: </h5>
<form class="form-group" action="{% url 'coupons:apply' %}" method="post">
{{ coupon_apply_form }}
<input type="submit" class="btn btn-default" value="Apply">
{% csrf_token %}
</form>

	<p class="text-right">
		<a href="{% url 'shop:product_list' %}" class="btn btn-default button">Continue shopping</a>
		<a class="btn btn-primary" href="{% url 'orders:order_create' %}">Checkout</a>
	</p>
</div>
{% endblock %}