cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'


urlpatterns = [
    path('',views.cart_detail , name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/',views.cart_remove , name='cart_remove'),
]

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'


urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
]

website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _



urlpatterns =  i18n_patterns(
    path(_('admin/'), admin.site.urls),
    path('rosetta/', include('rosetta.urls')),

    path(_('cart/'), include('cart.urls', namespace='cart')),
    path(_('orders/'), include('orders.urls', namespace='orders')),
    path(_('coupons/'), include('coupons.urls', namespace='coupons')),
    path('', include('shop.urls', namespace='shop')),
)
if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/base.html
{% load i18n %}
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>{% block title %} {% trans 'My shop' %}{% endblock title %}</title>
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
  <!-- Bootstrap core CSS -->
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <!-- Material Design Bootstrap -->
  <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
  <!-- Your custom styles (optional) -->
  <link href="{% static 'css/style.min.css' %}" rel="stylesheet">
  <style type="text/css">
    html,
    body,
    header,
    .carousel {
      height: 60vh;
    }

    @media (max-width: 740px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

    @media (min-width: 800px) and (max-width: 850px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

  </style>
</head>

<body>

  <!-- Navbar -->
  <nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
    <div class="container">

      <!-- Brand -->
      <a class="navbar-brand waves-effect" href="{% url 'shop:product_list' %}" >
        <strong class="blue-text">{% trans "My shop" %}</strong>
      </a>


      <!-- Collapse -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Links -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <!-- Left -->
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link waves-effect" href="{% url 'shop:product_list' %}">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="" >Categories</a>
          </li>
        </ul>

        <!-- Right -->
        <ul class="navbar-nav nav-flex-icons">
          <li class="nav-item">

		{% with total_items=cart|length %}
			{% if cart|length > 0 %}

			<a class="nav-link waves-effect"  href="{% url 'cart:cart_detail' %}">
		<span class="badge red z-depth-1 mr-1">{% blocktrans with total=cart.get_total_price count items=total_items %}
{{ items }} item, ${{ total }}
  {% plural %}
{{ items }} items, ${{ total }}
{% endblocktrans %}

</span>
			<i class="fas fa-shopping-cart"></i>
			<span class="clearfix d-none d-sm-inline-block"> {% trans "Your cart" %} </span>
			</a>
			{% else %}
			<a class="nav-link waves-effect"  href="{% url 'cart:cart_detail' %}">
			<span class="clearfix d-none d-sm-inline-block"> {% trans "Your cart is empty." %}</span>
			<i class="fas fa-shopping-cart"></i>
			</a>
			{% endif %}
			{% endwith %}

		  
      {% if user.is_authenticated %}
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-user"></i>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href=""><i class="fas fa-user-circle"></i> Profile</a>
          <a class="dropdown-item" href="#"><i class="fas fa-user-edit"></i> Edit Profile</a>
          <a class="dropdown-item" href=""><i class="far fa-edit"></i> Change Password</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href=""><i class="fas fa-shopping-cart"></i> My Orders</a>
		  <a class="dropdown-item" href=""><i class="fas fa-truck-moving"></i> Track Orders </a>
		  <div class="dropdown-divider"></div>
          <a class="dropdown-item" href=""><i class="fas fa-sign-in-alt "></i> Logout</a>
        </div>
      </li>	  
		  {% else %}
		  <li class="nav-item mr-2">
            <a href="" class="nav-link border border-light rounded waves-effect"
               >
               <i class="fas fa-sign-in-alt "></i>Login
            </a>
          </li>
          <li class="nav-item">
            <a href="" class="nav-link border border-light rounded waves-effect"
               >
               <i class="fas fa-user-plus"></i>Sign Up
            </a>
          </li>
		  {% endif %}
        </ul>

      </div>
{% get_current_language as LANGUAGE_CODE %}
{% get_available_languages as LANGUAGES %}
{% get_language_info_list for LANGUAGES as languages %}
<div class="languages">
<ul class="languages">
{% for language in languages %}
<li>
<a href="/{{ language.code }}/" {% if language.code == LANGUAGE_CODE %} class="selected" {%endif %}>
{{ language.name_local }}
</a>
</li>
{% endfor %}
</ul>
</div>
    </div>
  </nav>
  <!-- Navbar -->

{% block content %}
  
{% endblock content %}
  

  <!--Footer-->
  <footer class="page-footer text-center font-small mt-4 wow fadeIn">
    <hr class="my-4">

    <!-- Social icons -->
    <div class="pb-4">
      <a href=""  >
        <i class="fab fa-facebook-f mr-3"></i>
      </a>

      <a href=""  >
        <i class="fab fa-twitter mr-3"></i>
      </a>

      <a href=""  >
        <i class="fab fa-youtube mr-3"></i>
      </a>

      <a href=""  >
        <i class="fab fa-google-plus-g mr-3"></i>
      </a>

      <a href=""  >
        <i class="fab fa-dribbble mr-3"></i>
      </a>

      <a href=""  >
        <i class="fab fa-pinterest mr-3"></i>
      </a>

      <a href=""  >
        <i class="fab fa-github mr-3"></i>
      </a>

      <a href=""  >
        <i class="fab fa-codepen mr-3"></i>
      </a>
    </div>
    <!-- Social icons -->

    <!--Copyright-->
    <div class="footer-copyright py-3">
      © 2019 Copyright:
      <a href=""  > MDBootstrap.com </a>
    </div>
    <!--/.Copyright-->

  </footer>
  <!--/.Footer-->

  <!-- SCRIPTS -->
  <!-- JQuery -->
  <script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
  <!-- Bootstrap tooltips -->
  <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
  <!-- Bootstrap core JavaScript -->
  <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
  <!-- MDB core JavaScript -->
  <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
  <!-- Initializations -->
  <script type="text/javascript">
    // Animations initialization
    new WOW().init();

  </script>
</body>

</html>